import {
  type EmbeddedFormDefinitionV1,
  type EmbeddedFormFieldDef,
  embeddedDefinitionToJson,
} from "@/lib/embedded-form-definition";

const HEALTH_CONDITIONS: { value: string; label: string }[] = [
  { value: "poor_vision", label: "Poor vision" },
  { value: "eye_strain", label: "Eye strain" },
  { value: "poor_hearing", label: "Poor hearing" },
  { value: "noises_in_ears", label: "Noises in ears" },
  { value: "frequent_headaches", label: "Frequent headaches" },
  { value: "frequent_cold", label: "Frequent cold" },
  { value: "nose_bleeding", label: "Nose bleeding" },
  { value: "gum_bleeding", label: "Gum bleeding" },
  { value: "sinus_trouble", label: "Sinus trouble" },
  { value: "allergies", label: "Allergies" },
  { value: "shortness_of_breath", label: "Shortness of breath" },
  { value: "asthma", label: "Asthma" },
  { value: "chest_pain", label: "Chest pain" },
  { value: "bronchitis", label: "Bronchitis" },
  { value: "heart_palpitations", label: "Heart palpitations" },
  { value: "skin_diseases", label: "Skin diseases" },
  { value: "food_intolerance", label: "Food intolerance" },
  { value: "stomach_pains", label: "Stomach pains" },
  { value: "diarrhoea", label: "Diarrhoea" },
  { value: "frequent_constipation", label: "Frequent constipation" },
  { value: "muscle_or_bone_pain", label: "Muscle or bone pain" },
  { value: "mental_depression", label: "Mental depression" },
  { value: "sleep_trouble", label: "Sleep trouble" },
  { value: "frequent_urination", label: "Frequent urination" },
];

function f(
  partial: Omit<EmbeddedFormFieldDef, "visibility"> & { visibility?: EmbeddedFormFieldDef["visibility"] },
): EmbeddedFormFieldDef {
  return { visibility: "applicant", ...partial };
}

/** Complete Hebron Theological College B.Th. application template (fields 1–27 + registrar). */
export function createHtcApplicationDefinition(): EmbeddedFormDefinitionV1 {
  return {
    version: 1,
    templateKey: "htc-application",
    sections: [
      {
        id: "sec_personal",
        title: "Personal Information",
        description: "Please enter your details exactly as they appear on your academic certificate.",
        order: 0,
      },
      {
        id: "sec_family",
        title: "Family Information",
        order: 1,
      },
      {
        id: "sec_church",
        title: "Church & Spiritual Background",
        order: 2,
      },
      {
        id: "sec_ministry",
        title: "Ministry & Experience",
        order: 3,
      },
      {
        id: "sec_education",
        title: "Educational Qualification",
        description: "All applicable columns must be filled.",
        order: 4,
      },
      {
        id: "sec_motivation",
        title: "Motivation & Background",
        order: 5,
      },
      {
        id: "sec_health",
        title: "Health Declaration",
        order: 6,
      },
      {
        id: "sec_references",
        title: "References",
        description: "Persons who know you well (note any relationship to you).",
        order: 7,
      },
      {
        id: "sec_declaration",
        title: "Declaration and Pledge",
        order: 8,
      },
      {
        id: "sec_submission",
        title: "Application Materials & Fee",
        description:
          "Upload your academic documents, write your personal testimony, then pay the $50 application fee (card processing included).",
        order: 9,
      },
      {
        id: "sec_registrar",
        title: "For Registrar Use Only",
        description: "Staff only — not shown to applicants.",
        order: 10,
        adminOnly: true,
      },
    ],
    fields: [
      f({
        id: "f_photo",
        sectionId: "sec_personal",
        key: "passportPhoto",
        type: "photo",
        label: "Passport-size photo",
        required: true,
        order: -1,
        helperText: "Upload one clear recent passport-style photo (JPEG, PNG, or WebP).",
      }),
      f({
        id: "f_1",
        sectionId: "sec_personal",
        key: "fullName",
        type: "text",
        label: "1. Full name (block letters) — exactly as it appears on your academic certificate",
        required: true,
        order: 0,
        validation: { maxLength: 200 },
      }),
      f({
        id: "f_2",
        sectionId: "sec_personal",
        key: "sex",
        type: "radio",
        label: "2. Sex",
        required: true,
        order: 1,
        options: [
          { value: "Male", label: "Male" },
          { value: "Female", label: "Female" },
        ],
      }),
      f({
        id: "f_3_day",
        sectionId: "sec_personal",
        key: "dobDay",
        type: "number",
        label: "3. Day of birth",
        required: true,
        order: 2,
        layout: { groupKey: "dob", width: "quarter" },
        validation: { min: 1, max: 31 },
      }),
      f({
        id: "f_3_month",
        sectionId: "sec_personal",
        key: "dobMonth",
        type: "number",
        label: "Month",
        required: true,
        order: 4,
        layout: { groupKey: "dob", width: "quarter" },
        validation: { min: 1, max: 12 },
      }),
      f({
        id: "f_3_year",
        sectionId: "sec_personal",
        key: "dobYear",
        type: "number",
        label: "Year",
        required: true,
        order: 5,
        layout: { groupKey: "dob", width: "quarter" },
        validation: { min: 1920, max: 2020 },
      }),
      f({
        id: "f_3_age",
        sectionId: "sec_personal",
        key: "ageNow",
        type: "number",
        label: "Age now",
        required: false,
        order: 6,
        helperText: "Calculated automatically from your date of birth if left blank.",
        layout: { groupKey: "dob", width: "quarter" },
        validation: { min: 1, max: 120 },
      }),
      f({
        id: "f_4_nat",
        sectionId: "sec_personal",
        key: "nationality",
        type: "text",
        label: "4. Nationality",
        required: true,
        order: 7,
        layout: { groupKey: "geo", width: "third" },
      }),
      f({
        id: "f_4_state",
        sectionId: "sec_personal",
        key: "state",
        type: "text",
        label: "State",
        required: true,
        order: 8,
        layout: { groupKey: "geo", width: "third" },
      }),
      f({
        id: "f_4_county",
        sectionId: "sec_personal",
        key: "county",
        type: "text",
        label: "County",
        required: false,
        order: 9,
        layout: { groupKey: "geo", width: "third" },
      }),
      f({
        id: "f_5_occ",
        sectionId: "sec_personal",
        key: "occupation",
        type: "text",
        label: "5. Your occupation",
        required: true,
        order: 10,
        layout: { groupKey: "occ", width: "half" },
      }),
      f({
        id: "f_5_tongue",
        sectionId: "sec_personal",
        key: "motherTongue",
        type: "text",
        label: "Mother tongue",
        required: true,
        order: 11,
        layout: { groupKey: "occ", width: "half" },
      }),
      f({
        id: "f_6",
        sectionId: "sec_personal",
        key: "otherLanguages",
        type: "text",
        label: "6. Other languages you can speak, read and write",
        required: false,
        order: 12,
      }),
      f({
        id: "f_7_a1",
        sectionId: "sec_personal",
        key: "addressLine1",
        type: "text",
        label: "7. Address for communication — line 1",
        required: true,
        order: 13,
      }),
      f({
        id: "f_7_a2",
        sectionId: "sec_personal",
        key: "addressLine2",
        type: "text",
        label: "Address — line 2",
        required: false,
        order: 14,
      }),
      f({
        id: "f_email",
        sectionId: "sec_personal",
        key: "email",
        type: "email",
        label: "Email",
        required: true,
        order: 15,
        layout: { groupKey: "contact", width: "half" },
      }),
      f({
        id: "f_phone",
        sectionId: "sec_personal",
        key: "phone",
        type: "tel",
        label: "Phone",
        required: true,
        order: 16,
        layout: { groupKey: "contact", width: "half" },
      }),

      // Family
      f({
        id: "f_8_name",
        sectionId: "sec_family",
        key: "fatherGuardianName",
        type: "text",
        label: "8. Name of father / guardian",
        required: true,
        order: 0,
      }),
      f({
        id: "f_8_addr",
        sectionId: "sec_family",
        key: "fatherGuardianAddress",
        type: "textarea",
        label: "Address of father / guardian",
        required: true,
        order: 1,
      }),
      f({
        id: "f_9",
        sectionId: "sec_family",
        key: "fatherGuardianOccupation",
        type: "text",
        label: "9. Occupation of father / guardian",
        required: true,
        order: 2,
      }),
      f({
        id: "f_10_status",
        sectionId: "sec_family",
        key: "maritalStatus",
        type: "radio",
        label: "10. Marital status",
        required: true,
        order: 3,
        options: [
          { value: "Married", label: "Married" },
          { value: "Unmarried", label: "Unmarried" },
        ],
        layout: { groupKey: "marital", width: "half" },
      }),
      f({
        id: "f_10_date",
        sectionId: "sec_family",
        key: "dateOfMarriage",
        type: "text",
        label: "Date of marriage (if applicable)",
        required: false,
        order: 4,
        layout: { groupKey: "marital", width: "half" },
        showWhen: { fieldKey: "maritalStatus", equals: "Married" },
      }),
      f({
        id: "f_10_spouse",
        sectionId: "sec_family",
        key: "spouseName",
        type: "text",
        label: "Name of spouse",
        required: false,
        order: 5,
        showWhen: { fieldKey: "maritalStatus", equals: "Married" },
      }),
      f({
        id: "f_11_c1",
        sectionId: "sec_family",
        key: "child1NameAge",
        type: "text",
        label: "11. Child (I) — name & age",
        required: false,
        order: 6,
        layout: { groupKey: "children", width: "third" },
        showWhen: { fieldKey: "maritalStatus", equals: "Married" },
      }),
      f({
        id: "f_11_c2",
        sectionId: "sec_family",
        key: "child2NameAge",
        type: "text",
        label: "Child (II) — name & age",
        required: false,
        order: 7,
        layout: { groupKey: "children", width: "third" },
        showWhen: { fieldKey: "maritalStatus", equals: "Married" },
      }),
      f({
        id: "f_11_c3",
        sectionId: "sec_family",
        key: "child3NameAge",
        type: "text",
        label: "Child (III) — name & age",
        required: false,
        order: 8,
        layout: { groupKey: "children", width: "third" },
        showWhen: { fieldKey: "maritalStatus", equals: "Married" },
      }),

      // Church
      f({
        id: "f_12",
        sectionId: "sec_church",
        key: "churchAffiliation",
        type: "text",
        label: "12. Your church affiliation (denomination)",
        required: true,
        order: 0,
      }),
      f({
        id: "f_13_name",
        sectionId: "sec_church",
        key: "localChurchNameAddress",
        type: "textarea",
        label: "13. Name and address of your local church",
        required: true,
        order: 1,
      }),
      f({
        id: "f_13_phone",
        sectionId: "sec_church",
        key: "localChurchPhone",
        type: "tel",
        label: "Church phone",
        required: false,
        order: 2,
      }),
      f({
        id: "f_14",
        sectionId: "sec_church",
        key: "receivedJesusWhen",
        type: "text",
        label: "14. When did you receive Jesus Christ as your personal Saviour?",
        required: true,
        order: 3,
      }),
      f({
        id: "f_15",
        sectionId: "sec_church",
        key: "waterBaptismWhen",
        type: "text",
        label: "15. When did you receive water baptism?",
        required: true,
        order: 4,
      }),
      f({
        id: "f_16",
        sectionId: "sec_church",
        key: "filledWithHolySpirit",
        type: "textarea",
        label: "16. Are you filled with the Holy Spirit? (Acts 2:4)",
        required: true,
        order: 5,
      }),
      f({
        id: "f_17",
        sectionId: "sec_church",
        key: "definiteCallForService",
        type: "textarea",
        label: "17. Do you have a definite call for Christian service?",
        required: true,
        order: 6,
      }),

      // Ministry
      f({
        id: "f_18",
        sectionId: "sec_ministry",
        key: "ordainedPastor",
        type: "radio",
        label: "18. Are you an ordained pastor?",
        required: true,
        order: 0,
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
        ],
      }),
      f({
        id: "f_18_detail",
        sectionId: "sec_ministry",
        key: "ordinationDetails",
        type: "textarea",
        label: "If yes — date of ordination and the church where you minister",
        required: false,
        order: 1,
        showWhen: { fieldKey: "ordainedPastor", equals: "Yes" },
      }),
      f({
        id: "f_19",
        sectionId: "sec_ministry",
        key: "sinceHighSchool",
        type: "textarea",
        label: "19. What have you done since leaving high school? (work and study)",
        required: true,
        order: 2,
      }),
      f({
        id: "f_20",
        sectionId: "sec_ministry",
        key: "christianMinistryDetails",
        type: "textarea",
        label: "20. Are you involved in any Christian ministry? If so, give details",
        required: true,
        order: 3,
      }),
      f({
        id: "f_21",
        sectionId: "sec_ministry",
        key: "awardsReceived",
        type: "textarea",
        label: "21. Awards received in sports, games, music, artwork, literary or other activity",
        required: false,
        order: 4,
      }),

      // Education — applicants add only the rows they need
      f({
        id: "f_22_entries",
        sectionId: "sec_education",
        key: "educationEntries",
        type: "educationEntries",
        label: "22. Educational qualification",
        required: true,
        order: 0,
        helperText: "Add each applicable level. All columns should be filled for every row you add.",
        options: [
          { value: "High School", label: "High School" },
          { value: "Undergrad", label: "Undergrad" },
          { value: "Graduate School", label: "Graduate School" },
          { value: "Other, if any", label: "Other, if any" },
        ],
      }),

      // Motivation
      f({
        id: "f_23",
        sectionId: "sec_motivation",
        key: "whyJoinProgramme",
        type: "textarea",
        label: "23. Why would you like to join this programme?",
        required: true,
        order: 0,
      }),
      f({
        id: "f_24",
        sectionId: "sec_motivation",
        key: "discontinuedStudies",
        type: "textarea",
        label: "24. Have you ever discontinued any studies? If so, why?",
        required: false,
        order: 1,
      }),

      // Health
      f({
        id: "f_25",
        sectionId: "sec_health",
        key: "healthConditions",
        type: "checkboxGroup",
        label: "25. Check any of the following you currently suffer from",
        required: false,
        order: 0,
        options: HEALTH_CONDITIONS,
      }),
      f({
        id: "f_26_illness",
        sectionId: "sec_health",
        key: "illnessHistory",
        type: "textarea",
        label: "26. List any illness you have had",
        required: false,
        order: 1,
        layout: { groupKey: "illness", width: "half" },
      }),
      f({
        id: "f_26_now",
        sectionId: "sec_health",
        key: "illnessStatusNow",
        type: "textarea",
        label: "How is it now?",
        required: false,
        order: 2,
        layout: { groupKey: "illness", width: "half" },
      }),

      // References
      f({
        id: "f_27a_name",
        sectionId: "sec_references",
        key: "refPastorName",
        type: "text",
        label: "27. (a) Your pastor — name",
        required: true,
        order: 0,
      }),
      f({
        id: "f_27a_addr",
        sectionId: "sec_references",
        key: "refPastorAddress",
        type: "text",
        label: "Address",
        required: true,
        order: 1,
        layout: { groupKey: "ref_a", width: "half" },
      }),
      f({
        id: "f_27a_phone",
        sectionId: "sec_references",
        key: "refPastorPhone",
        type: "tel",
        label: "Phone",
        required: true,
        order: 2,
        layout: { groupKey: "ref_a", width: "half" },
      }),
      f({
        id: "f_27b_name",
        sectionId: "sec_references",
        key: "refOfficialName",
        type: "text",
        label: "(b) An official of your local church / mission / organization — name",
        required: true,
        order: 3,
      }),
      f({
        id: "f_27b_addr",
        sectionId: "sec_references",
        key: "refOfficialAddress",
        type: "text",
        label: "Address",
        required: true,
        order: 4,
        layout: { groupKey: "ref_b", width: "half" },
      }),
      f({
        id: "f_27b_phone",
        sectionId: "sec_references",
        key: "refOfficialPhone",
        type: "tel",
        label: "Phone",
        required: true,
        order: 5,
        layout: { groupKey: "ref_b", width: "half" },
      }),
      f({
        id: "f_27c_name",
        sectionId: "sec_references",
        key: "refFriendName",
        type: "text",
        label:
          "(c) A responsible Christian friend outside your local church, employer or teacher — name",
        required: true,
        order: 6,
      }),
      f({
        id: "f_27c_addr",
        sectionId: "sec_references",
        key: "refFriendAddress",
        type: "text",
        label: "Address",
        required: true,
        order: 7,
        layout: { groupKey: "ref_c", width: "half" },
      }),
      f({
        id: "f_27c_phone",
        sectionId: "sec_references",
        key: "refFriendPhone",
        type: "tel",
        label: "Phone",
        required: true,
        order: 8,
        layout: { groupKey: "ref_c", width: "half" },
      }),

      // Declaration
      f({
        id: "f_decl_text",
        sectionId: "sec_declaration",
        key: "declarationText",
        type: "staticText",
        label: "Declaration",
        required: false,
        order: 0,
        helperText:
          "I hereby declare that every piece of information given above is true and correct. If I am admitted to Hebron Theological College, I promise that: (a) I shall try to promote and maintain high academic standards and a spirit of unity and love. (b) I shall abide by the rules and regulations of Hebron Theological College. (c) I shall submit myself to the right of the College administration to take any appropriate disciplinary action against me if, in their judgement, my behaviour, approach or doctrine is found contrary to the spirit and concern of Hebron Theological College.",
      }),
      f({
        id: "f_decl_accept",
        sectionId: "sec_declaration",
        key: "declarationAccepted",
        type: "declaration",
        label: "I have read and agree to the declaration and pledge above",
        required: true,
        order: 1,
      }),
      f({
        id: "f_decl_name",
        sectionId: "sec_declaration",
        key: "declarationName",
        type: "text",
        label: "Name",
        required: true,
        order: 2,
      }),
      f({
        id: "f_sig_date",
        sectionId: "sec_declaration",
        key: "applicantSignatureDate",
        type: "date",
        label: "Date",
        required: true,
        order: 3,
        layout: { groupKey: "sig", width: "half" },
      }),
      f({
        id: "f_sig",
        sectionId: "sec_declaration",
        key: "applicantSignature",
        type: "signatureTyped",
        label: "Signature of the applicant (type your full legal name)",
        required: true,
        order: 4,
        layout: { groupKey: "sig", width: "half" },
      }),

      // Digital submission materials (replaces paper instructions page)
      f({
        id: "f_testimony",
        sectionId: "sec_submission",
        key: "personalTestimony",
        type: "textarea",
        label: "Personal testimony",
        required: true,
        order: 0,
        helperText: "Share your personal testimony in your own words.",
        placeholder: "Write your personal testimony here…",
        validation: { minLength: 40 },
      }),
      f({
        id: "f_academic_docs",
        sectionId: "sec_submission",
        key: "academicDocuments",
        type: "documentUploads",
        label: "Academic documents",
        required: true,
        order: 1,
        helperText: "Upload up to 5 academic certificates or transcripts (PDF, JPEG, PNG, or WebP — 5 MB each).",
        validation: { max: 5 },
      }),
      f({
        id: "f_fee_note",
        sectionId: "sec_submission",
        key: "applicationFeeNote",
        type: "staticText",
        label: "Application fee",
        required: false,
        order: 2,
        helperText:
          "A $50 (US) application fee is required. Card processing is included in the checkout total so the college receives the full $50. You will be redirected to secure Stripe Checkout after you submit.",
      }),

      // Registrar (admin only)
      f({
        id: "f_reg_received",
        sectionId: "sec_registrar",
        key: "registrarDateReceived",
        type: "date",
        label: "Date of receiving application",
        required: false,
        order: 0,
        visibility: "admin",
      }),
      f({
        id: "f_reg_fees",
        sectionId: "sec_registrar",
        key: "registrarFeesReceived",
        type: "text",
        label: "Fees — application / late fee received ($)",
        required: false,
        order: 1,
        visibility: "admin",
      }),
      f({
        id: "f_reg_appno",
        sectionId: "sec_registrar",
        key: "registrarApplicationNumber",
        type: "text",
        label: "Application number",
        required: false,
        order: 2,
        visibility: "admin",
        helperText: "Defaults to the system application number if left blank.",
      }),
      f({
        id: "f_reg_decision",
        sectionId: "sec_registrar",
        key: "registrarAdmissionDecision",
        type: "radio",
        label: "Admission",
        required: false,
        order: 3,
        visibility: "admin",
        options: [
          { value: "Approved", label: "Approved" },
          { value: "Rejected", label: "Rejected" },
          { value: "Referred", label: "Referred" },
        ],
      }),
      f({
        id: "f_reg_date",
        sectionId: "sec_registrar",
        key: "registrarDecisionDate",
        type: "date",
        label: "Date",
        required: false,
        order: 4,
        visibility: "admin",
      }),
      f({
        id: "f_reg_sig",
        sectionId: "sec_registrar",
        key: "registrarSignature",
        type: "signatureTyped",
        label: "Signature",
        required: false,
        order: 5,
        visibility: "admin",
      }),
    ],
  };
}

export function htcApplicationDefinitionJson(): string {
  return embeddedDefinitionToJson(createHtcApplicationDefinition());
}

export const HTC_FORM_DEFAULTS = {
  title: "Application for Admission",
  subtitle: "Bachelor of Theology (B.Th.)",
  slug: "htc-application",
  emailFromName: "Hebron Theological College",
  emailSubject: "Application received — Hebron Theological College",
  helpEmail: "admissions@ipchouston.com",
  helpPhone: "(713) 555-0148",
  pdfTemplateKey: "htc-application",
  applicationNumberPrefix: "HTC",
  welcomeMessage:
    "Thank you for your interest in Hebron Theological College. Please complete every section carefully. Start with your passport photo and personal details, then finish with academic documents, your personal testimony, and the $50 application fee online.",
  confirmationMessage:
    "Your application and payment have been received. Someone from our admissions team will review your materials and contact you.",
  instructions:
    "Digital submission: (1) Passport-size photo on the first page (2) Academic documents — up to 5 files (3) Written personal testimony (4) $50 application fee paid by card (processing included).",
  stripeAmountCents: 5000,
  stripeProductLabel: "Hebron Theological College — Application Fee",
} as const;
